[2024-02-12T11:42:40.021+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_DAG_V3.18.create_db_schem scheduled__2024-02-12T01:46:00+00:00 [queued]>
[2024-02-12T11:42:40.064+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_DAG_V3.18.create_db_schem scheduled__2024-02-12T01:46:00+00:00 [queued]>
[2024-02-12T11:42:40.066+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-12T11:42:40.154+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_db_schem> on 2024-02-12 01:46:00+00:00
[2024-02-12T11:42:40.169+0000] {standard_task_runner.py:60} INFO - Started process 9415 to run task
[2024-02-12T11:42:40.193+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Weather_DAG_V3.18', 'create_db_schem', 'scheduled__2024-02-12T01:46:00+00:00', '--job-id', '7861', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmpvn4j6y_m']
[2024-02-12T11:42:40.197+0000] {standard_task_runner.py:88} INFO - Job 7861: Subtask create_db_schem
[2024-02-12T11:42:40.404+0000] {task_command.py:423} INFO - Running <TaskInstance: Weather_DAG_V3.18.create_db_schem scheduled__2024-02-12T01:46:00+00:00 [running]> on host 06573eafe810
[2024-02-12T11:42:40.709+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_DAG_V3.18' AIRFLOW_CTX_TASK_ID='create_db_schem' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T01:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T01:46:00+00:00'
[2024-02-12T11:42:40.710+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS weather_tabb(
            city varchar,
            dt data,
            houur smallint,
            temperature_c float,
            pressure_mm float,
            is_rainy boolean
            )
[2024-02-12T11:42:40.753+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-12T11:42:40.765+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-12T11:42:40.781+0000] {sql.py:450} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS weather_tabb(
            city varchar,
            dt data,
            houur smallint,
            temperature_c float,
            pressure_mm float,
            is_rainy boolean
            ), parameters: None
[2024-02-12T11:42:40.787+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "data" does not exist
LINE 4:             dt data,
                       ^

[2024-02-12T11:42:40.806+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Weather_DAG_V3.18, task_id=create_db_schem, execution_date=20240212T014600, start_date=20240212T114240, end_date=20240212T114240
[2024-02-12T11:42:40.846+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7861 for task create_db_schem (type "data" does not exist
LINE 4:             dt data,
                       ^
; 9415)
[2024-02-12T11:42:40.874+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-12T11:42:40.908+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
